name = 'ts-cloudflare-worker-shortlinks'
type = 'javascript'

account_id = 'YOUR_ACCOUNT_ID' # Your Account ID
route = '' # Base domain for your shotlinks, e.g. links.example.com/*
zone_id = '' # Your zone ID in Cloudflare for your domain
usage_model = ''

compatibility_flags = []
compatibility_date = '2022-01-08'
workers_dev = true

[build]
command = 'npm run build'
# On M1 Mac if you have problems, use
# command = 'npm install && npm run build'
# the first time you build
watch_dir = 'src'
[build.upload]
format = 'service-worker'
